// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/lsmdb/v1/lsmdb.proto

package lsmdbv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Command_Operation int32

const (
	Command_OPERATION_NOOP   Command_Operation = 0
	Command_OPERATION_PUT    Command_Operation = 1
	Command_OPERATION_DELETE Command_Operation = 2
)

// Enum value maps for Command_Operation.
var (
	Command_Operation_name = map[int32]string{
		0: "OPERATION_NOOP",
		1: "OPERATION_PUT",
		2: "OPERATION_DELETE",
	}
	Command_Operation_value = map[string]int32{
		"OPERATION_NOOP":   0,
		"OPERATION_PUT":    1,
		"OPERATION_DELETE": 2,
	}
)

func (x Command_Operation) Enum() *Command_Operation {
	p := new(Command_Operation)
	*p = x
	return p
}

func (x Command_Operation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Command_Operation) Descriptor() protoreflect.EnumDescriptor {
	return file_api_lsmdb_v1_lsmdb_proto_enumTypes[0].Descriptor()
}

func (Command_Operation) Type() protoreflect.EnumType {
	return &file_api_lsmdb_v1_lsmdb_proto_enumTypes[0]
}

func (x Command_Operation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Command_Operation.Descriptor instead.
func (Command_Operation) EnumDescriptor() ([]byte, []int) {
	return file_api_lsmdb_v1_lsmdb_proto_rawDescGZIP(), []int{15, 0}
}

type PutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	ClientId      string                 `protobuf:"bytes,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	RequestSeq    uint64                 `protobuf:"varint,4,opt,name=request_seq,json=requestSeq,proto3" json:"request_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	mi := &file_api_lsmdb_v1_lsmdb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_lsmdb_v1_lsmdb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_api_lsmdb_v1_lsmdb_proto_rawDescGZIP(), []int{0}
}

func (x *PutRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *PutRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *PutRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *PutRequest) GetRequestSeq() uint64 {
	if x != nil {
		return x.RequestSeq
	}
	return 0
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	ClientId      string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	RequestSeq    uint64                 `protobuf:"varint,3,opt,name=request_seq,json=requestSeq,proto3" json:"request_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_api_lsmdb_v1_lsmdb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_lsmdb_v1_lsmdb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_api_lsmdb_v1_lsmdb_proto_rawDescGZIP(), []int{1}
}

func (x *DeleteRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *DeleteRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *DeleteRequest) GetRequestSeq() uint64 {
	if x != nil {
		return x.RequestSeq
	}
	return 0
}

type WriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          uint64                 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	LogIndex      uint64                 `protobuf:"varint,2,opt,name=log_index,json=logIndex,proto3" json:"log_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteResponse) Reset() {
	*x = WriteResponse{}
	mi := &file_api_lsmdb_v1_lsmdb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteResponse) ProtoMessage() {}

func (x *WriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_lsmdb_v1_lsmdb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteResponse.ProtoReflect.Descriptor instead.
func (*WriteResponse) Descriptor() ([]byte, []int) {
	return file_api_lsmdb_v1_lsmdb_proto_rawDescGZIP(), []int{2}
}

func (x *WriteResponse) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *WriteResponse) GetLogIndex() uint64 {
	if x != nil {
		return x.LogIndex
	}
	return 0
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_api_lsmdb_v1_lsmdb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_lsmdb_v1_lsmdb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_api_lsmdb_v1_lsmdb_proto_rawDescGZIP(), []int{3}
}

func (x *GetRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	ReadIndex     uint64                 `protobuf:"varint,3,opt,name=read_index,json=readIndex,proto3" json:"read_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_api_lsmdb_v1_lsmdb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_lsmdb_v1_lsmdb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_api_lsmdb_v1_lsmdb_proto_rawDescGZIP(), []int{4}
}

func (x *GetResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GetResponse) GetReadIndex() uint64 {
	if x != nil {
		return x.ReadIndex
	}
	return 0
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_api_lsmdb_v1_lsmdb_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_lsmdb_v1_lsmdb_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_api_lsmdb_v1_lsmdb_proto_rawDescGZIP(), []int{5}
}

type Peer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Peer) Reset() {
	*x = Peer{}
	mi := &file_api_lsmdb_v1_lsmdb_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Peer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Peer) ProtoMessage() {}

func (x *Peer) ProtoReflect() protoreflect.Message {
	mi := &file_api_lsmdb_v1_lsmdb_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Peer.ProtoReflect.Descriptor instead.
func (*Peer) Descriptor() ([]byte, []int) {
	return file_api_lsmdb_v1_lsmdb_proto_rawDescGZIP(), []int{6}
}

func (x *Peer) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Peer) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type StatusResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	NodeId             uint64                 `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Role               string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Term               uint64                 `protobuf:"varint,3,opt,name=term,proto3" json:"term,omitempty"`
	LeaderId           uint64                 `protobuf:"varint,4,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	CommitIndex        uint64                 `protobuf:"varint,5,opt,name=commit_index,json=commitIndex,proto3" json:"commit_index,omitempty"`
	AppliedIndex       uint64                 `protobuf:"varint,6,opt,name=applied_index,json=appliedIndex,proto3" json:"applied_index,omitempty"`
	Peers              []*Peer                `protobuf:"bytes,7,rep,name=peers,proto3" json:"peers,omitempty"`
	SnapshotIndex      uint64                 `protobuf:"varint,8,opt,name=snapshot_index,json=snapshotIndex,proto3" json:"snapshot_index,omitempty"`
	RetainedLogEntries uint64                 `protobuf:"varint,9,opt,name=retained_log_entries,json=retainedLogEntries,proto3" json:"retained_log_entries,omitempty"`
	VoterIds           []uint64               `protobuf:"varint,10,rep,packed,name=voter_ids,json=voterIds,proto3" json:"voter_ids,omitempty"`
	JointVoterIds      []uint64               `protobuf:"varint,11,rep,packed,name=joint_voter_ids,json=jointVoterIds,proto3" json:"joint_voter_ids,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_api_lsmdb_v1_lsmdb_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_lsmdb_v1_lsmdb_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_api_lsmdb_v1_lsmdb_proto_rawDescGZIP(), []int{7}
}

func (x *StatusResponse) GetNodeId() uint64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *StatusResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *StatusResponse) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *StatusResponse) GetLeaderId() uint64 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

func (x *StatusResponse) GetCommitIndex() uint64 {
	if x != nil {
		return x.CommitIndex
	}
	return 0
}

func (x *StatusResponse) GetAppliedIndex() uint64 {
	if x != nil {
		return x.AppliedIndex
	}
	return 0
}

func (x *StatusResponse) GetPeers() []*Peer {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *StatusResponse) GetSnapshotIndex() uint64 {
	if x != nil {
		return x.SnapshotIndex
	}
	return 0
}

func (x *StatusResponse) GetRetainedLogEntries() uint64 {
	if x != nil {
		return x.RetainedLogEntries
	}
	return 0
}

func (x *StatusResponse) GetVoterIds() []uint64 {
	if x != nil {
		return x.VoterIds
	}
	return nil
}

func (x *StatusResponse) GetJointVoterIds() []uint64 {
	if x != nil {
		return x.JointVoterIds
	}
	return nil
}

type ChangeMembershipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VoterIds      []uint64               `protobuf:"varint,1,rep,packed,name=voter_ids,json=voterIds,proto3" json:"voter_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeMembershipRequest) Reset() {
	*x = ChangeMembershipRequest{}
	mi := &file_api_lsmdb_v1_lsmdb_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeMembershipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeMembershipRequest) ProtoMessage() {}

func (x *ChangeMembershipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_lsmdb_v1_lsmdb_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeMembershipRequest.ProtoReflect.Descriptor instead.
func (*ChangeMembershipRequest) Descriptor() ([]byte, []int) {
	return file_api_lsmdb_v1_lsmdb_proto_rawDescGZIP(), []int{8}
}

func (x *ChangeMembershipRequest) GetVoterIds() []uint64 {
	if x != nil {
		return x.VoterIds
	}
	return nil
}

type ChangeMembershipResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          uint64                 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	LogIndex      uint64                 `protobuf:"varint,2,opt,name=log_index,json=logIndex,proto3" json:"log_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeMembershipResponse) Reset() {
	*x = ChangeMembershipResponse{}
	mi := &file_api_lsmdb_v1_lsmdb_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeMembershipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeMembershipResponse) ProtoMessage() {}

func (x *ChangeMembershipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_lsmdb_v1_lsmdb_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeMembershipResponse.ProtoReflect.Descriptor instead.
func (*ChangeMembershipResponse) Descriptor() ([]byte, []int) {
	return file_api_lsmdb_v1_lsmdb_proto_rawDescGZIP(), []int{9}
}

func (x *ChangeMembershipResponse) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *ChangeMembershipResponse) GetLogIndex() uint64 {
	if x != nil {
		return x.LogIndex
	}
	return 0
}

// NotLeader is attached to FailedPrecondition gRPC statuses.
type NotLeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaderId      uint64                 `protobuf:"varint,1,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	LeaderAddress string                 `protobuf:"bytes,2,opt,name=leader_address,json=leaderAddress,proto3" json:"leader_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotLeader) Reset() {
	*x = NotLeader{}
	mi := &file_api_lsmdb_v1_lsmdb_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotLeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotLeader) ProtoMessage() {}

func (x *NotLeader) ProtoReflect() protoreflect.Message {
	mi := &file_api_lsmdb_v1_lsmdb_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotLeader.ProtoReflect.Descriptor instead.
func (*NotLeader) Descriptor() ([]byte, []int) {
	return file_api_lsmdb_v1_lsmdb_proto_rawDescGZIP(), []int{10}
}

func (x *NotLeader) GetLeaderId() uint64 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

func (x *NotLeader) GetLeaderAddress() string {
	if x != nil {
		return x.LeaderAddress
	}
	return ""
}

type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint64                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Term          uint64                 `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_api_lsmdb_v1_lsmdb_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_api_lsmdb_v1_lsmdb_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_api_lsmdb_v1_lsmdb_proto_rawDescGZIP(), []int{11}
}

func (x *LogEntry) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *LogEntry) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *LogEntry) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type RaftMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          uint32                 `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	From          uint64                 `protobuf:"varint,2,opt,name=from,proto3" json:"from,omitempty"`
	To            uint64                 `protobuf:"varint,3,opt,name=to,proto3" json:"to,omitempty"`
	Term          uint64                 `protobuf:"varint,4,opt,name=term,proto3" json:"term,omitempty"`
	LogIndex      uint64                 `protobuf:"varint,5,opt,name=log_index,json=logIndex,proto3" json:"log_index,omitempty"`
	LogTerm       uint64                 `protobuf:"varint,6,opt,name=log_term,json=logTerm,proto3" json:"log_term,omitempty"`
	Entries       []*LogEntry            `protobuf:"bytes,7,rep,name=entries,proto3" json:"entries,omitempty"`
	LeaderCommit  uint64                 `protobuf:"varint,8,opt,name=leader_commit,json=leaderCommit,proto3" json:"leader_commit,omitempty"`
	Reject        bool                   `protobuf:"varint,9,opt,name=reject,proto3" json:"reject,omitempty"`
	RejectHint    uint64                 `protobuf:"varint,10,opt,name=reject_hint,json=rejectHint,proto3" json:"reject_hint,omitempty"`
	Context       uint64                 `protobuf:"varint,11,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftMessage) Reset() {
	*x = RaftMessage{}
	mi := &file_api_lsmdb_v1_lsmdb_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftMessage) ProtoMessage() {}

func (x *RaftMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_lsmdb_v1_lsmdb_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftMessage.ProtoReflect.Descriptor instead.
func (*RaftMessage) Descriptor() ([]byte, []int) {
	return file_api_lsmdb_v1_lsmdb_proto_rawDescGZIP(), []int{12}
}

func (x *RaftMessage) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *RaftMessage) GetFrom() uint64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *RaftMessage) GetTo() uint64 {
	if x != nil {
		return x.To
	}
	return 0
}

func (x *RaftMessage) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *RaftMessage) GetLogIndex() uint64 {
	if x != nil {
		return x.LogIndex
	}
	return 0
}

func (x *RaftMessage) GetLogTerm() uint64 {
	if x != nil {
		return x.LogTerm
	}
	return 0
}

func (x *RaftMessage) GetEntries() []*LogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *RaftMessage) GetLeaderCommit() uint64 {
	if x != nil {
		return x.LeaderCommit
	}
	return 0
}

func (x *RaftMessage) GetReject() bool {
	if x != nil {
		return x.Reject
	}
	return false
}

func (x *RaftMessage) GetRejectHint() uint64 {
	if x != nil {
		return x.RejectHint
	}
	return 0
}

func (x *RaftMessage) GetContext() uint64 {
	if x != nil {
		return x.Context
	}
	return 0
}

type RaftAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftAck) Reset() {
	*x = RaftAck{}
	mi := &file_api_lsmdb_v1_lsmdb_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftAck) ProtoMessage() {}

func (x *RaftAck) ProtoReflect() protoreflect.Message {
	mi := &file_api_lsmdb_v1_lsmdb_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftAck.ProtoReflect.Descriptor instead.
func (*RaftAck) Descriptor() ([]byte, []int) {
	return file_api_lsmdb_v1_lsmdb_proto_rawDescGZIP(), []int{13}
}

type SnapshotChunk struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	From            uint64                 `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"`
	To              uint64                 `protobuf:"varint,2,opt,name=to,proto3" json:"to,omitempty"`
	RaftTerm        uint64                 `protobuf:"varint,3,opt,name=raft_term,json=raftTerm,proto3" json:"raft_term,omitempty"`
	SnapshotIndex   uint64                 `protobuf:"varint,4,opt,name=snapshot_index,json=snapshotIndex,proto3" json:"snapshot_index,omitempty"`
	SnapshotTerm    uint64                 `protobuf:"varint,5,opt,name=snapshot_term,json=snapshotTerm,proto3" json:"snapshot_term,omitempty"`
	Offset          uint64                 `protobuf:"varint,6,opt,name=offset,proto3" json:"offset,omitempty"`
	TotalSize       uint64                 `protobuf:"varint,7,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	Checksum        uint32                 `protobuf:"varint,8,opt,name=checksum,proto3" json:"checksum,omitempty"`
	Data            []byte                 `protobuf:"bytes,9,opt,name=data,proto3" json:"data,omitempty"`
	Voters          []uint64               `protobuf:"varint,10,rep,packed,name=voters,proto3" json:"voters,omitempty"`
	JointVoters     []uint64               `protobuf:"varint,11,rep,packed,name=joint_voters,json=jointVoters,proto3" json:"joint_voters,omitempty"`
	MembershipIndex uint64                 `protobuf:"varint,12,opt,name=membership_index,json=membershipIndex,proto3" json:"membership_index,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SnapshotChunk) Reset() {
	*x = SnapshotChunk{}
	mi := &file_api_lsmdb_v1_lsmdb_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotChunk) ProtoMessage() {}

func (x *SnapshotChunk) ProtoReflect() protoreflect.Message {
	mi := &file_api_lsmdb_v1_lsmdb_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotChunk.ProtoReflect.Descriptor instead.
func (*SnapshotChunk) Descriptor() ([]byte, []int) {
	return file_api_lsmdb_v1_lsmdb_proto_rawDescGZIP(), []int{14}
}

func (x *SnapshotChunk) GetFrom() uint64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *SnapshotChunk) GetTo() uint64 {
	if x != nil {
		return x.To
	}
	return 0
}

func (x *SnapshotChunk) GetRaftTerm() uint64 {
	if x != nil {
		return x.RaftTerm
	}
	return 0
}

func (x *SnapshotChunk) GetSnapshotIndex() uint64 {
	if x != nil {
		return x.SnapshotIndex
	}
	return 0
}

func (x *SnapshotChunk) GetSnapshotTerm() uint64 {
	if x != nil {
		return x.SnapshotTerm
	}
	return 0
}

func (x *SnapshotChunk) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *SnapshotChunk) GetTotalSize() uint64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *SnapshotChunk) GetChecksum() uint32 {
	if x != nil {
		return x.Checksum
	}
	return 0
}

func (x *SnapshotChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SnapshotChunk) GetVoters() []uint64 {
	if x != nil {
		return x.Voters
	}
	return nil
}

func (x *SnapshotChunk) GetJointVoters() []uint64 {
	if x != nil {
		return x.JointVoters
	}
	return nil
}

func (x *SnapshotChunk) GetMembershipIndex() uint64 {
	if x != nil {
		return x.MembershipIndex
	}
	return 0
}

// Command is the deterministic payload stored in the Raft log.
type Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operation     Command_Operation      `protobuf:"varint,1,opt,name=operation,proto3,enum=lsmdb.v1.Command_Operation" json:"operation,omitempty"`
	Key           []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	ClientId      string                 `protobuf:"bytes,4,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	RequestSeq    uint64                 `protobuf:"varint,5,opt,name=request_seq,json=requestSeq,proto3" json:"request_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_api_lsmdb_v1_lsmdb_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_api_lsmdb_v1_lsmdb_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_api_lsmdb_v1_lsmdb_proto_rawDescGZIP(), []int{15}
}

func (x *Command) GetOperation() Command_Operation {
	if x != nil {
		return x.Operation
	}
	return Command_OPERATION_NOOP
}

func (x *Command) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *Command) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Command) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *Command) GetRequestSeq() uint64 {
	if x != nil {
		return x.RequestSeq
	}
	return 0
}

var File_api_lsmdb_v1_lsmdb_proto protoreflect.FileDescriptor

const file_api_lsmdb_v1_lsmdb_proto_rawDesc = "" +
	"\n" +
	"\x18api/lsmdb/v1/lsmdb.proto\x12\blsmdb.v1\"r\n" +
	"\n" +
	"PutRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x1b\n" +
	"\tclient_id\x18\x03 \x01(\tR\bclientId\x12\x1f\n" +
	"\vrequest_seq\x18\x04 \x01(\x04R\n" +
	"requestSeq\"_\n" +
	"\rDeleteRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12\x1f\n" +
	"\vrequest_seq\x18\x03 \x01(\x04R\n" +
	"requestSeq\"@\n" +
	"\rWriteResponse\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x04R\x04term\x12\x1b\n" +
	"\tlog_index\x18\x02 \x01(\x04R\blogIndex\"\x1e\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\"X\n" +
	"\vGetResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x1d\n" +
	"\n" +
	"read_index\x18\x03 \x01(\x04R\treadIndex\"\x0f\n" +
	"\rStatusRequest\"0\n" +
	"\x04Peer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"\xfa\x02\n" +
	"\x0eStatusResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x04R\x06nodeId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x12\n" +
	"\x04term\x18\x03 \x01(\x04R\x04term\x12\x1b\n" +
	"\tleader_id\x18\x04 \x01(\x04R\bleaderId\x12!\n" +
	"\fcommit_index\x18\x05 \x01(\x04R\vcommitIndex\x12#\n" +
	"\rapplied_index\x18\x06 \x01(\x04R\fappliedIndex\x12$\n" +
	"\x05peers\x18\a \x03(\v2\x0e.lsmdb.v1.PeerR\x05peers\x12%\n" +
	"\x0esnapshot_index\x18\b \x01(\x04R\rsnapshotIndex\x120\n" +
	"\x14retained_log_entries\x18\t \x01(\x04R\x12retainedLogEntries\x12\x1b\n" +
	"\tvoter_ids\x18\n" +
	" \x03(\x04R\bvoterIds\x12&\n" +
	"\x0fjoint_voter_ids\x18\v \x03(\x04R\rjointVoterIds\"6\n" +
	"\x17ChangeMembershipRequest\x12\x1b\n" +
	"\tvoter_ids\x18\x01 \x03(\x04R\bvoterIds\"K\n" +
	"\x18ChangeMembershipResponse\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x04R\x04term\x12\x1b\n" +
	"\tlog_index\x18\x02 \x01(\x04R\blogIndex\"O\n" +
	"\tNotLeader\x12\x1b\n" +
	"\tleader_id\x18\x01 \x01(\x04R\bleaderId\x12%\n" +
	"\x0eleader_address\x18\x02 \x01(\tR\rleaderAddress\"H\n" +
	"\bLogEntry\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x04R\x05index\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x04R\x04term\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"\xbd\x02\n" +
	"\vRaftMessage\x12\x12\n" +
	"\x04type\x18\x01 \x01(\rR\x04type\x12\x12\n" +
	"\x04from\x18\x02 \x01(\x04R\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\x04R\x02to\x12\x12\n" +
	"\x04term\x18\x04 \x01(\x04R\x04term\x12\x1b\n" +
	"\tlog_index\x18\x05 \x01(\x04R\blogIndex\x12\x19\n" +
	"\blog_term\x18\x06 \x01(\x04R\alogTerm\x12,\n" +
	"\aentries\x18\a \x03(\v2\x12.lsmdb.v1.LogEntryR\aentries\x12#\n" +
	"\rleader_commit\x18\b \x01(\x04R\fleaderCommit\x12\x16\n" +
	"\x06reject\x18\t \x01(\bR\x06reject\x12\x1f\n" +
	"\vreject_hint\x18\n" +
	" \x01(\x04R\n" +
	"rejectHint\x12\x18\n" +
	"\acontext\x18\v \x01(\x04R\acontextJ\x04\b\f\x10\x0f\"\t\n" +
	"\aRaftAck\"\xe9\x02\n" +
	"\rSnapshotChunk\x12\x12\n" +
	"\x04from\x18\x01 \x01(\x04R\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\x04R\x02to\x12\x1b\n" +
	"\traft_term\x18\x03 \x01(\x04R\braftTerm\x12%\n" +
	"\x0esnapshot_index\x18\x04 \x01(\x04R\rsnapshotIndex\x12#\n" +
	"\rsnapshot_term\x18\x05 \x01(\x04R\fsnapshotTerm\x12\x16\n" +
	"\x06offset\x18\x06 \x01(\x04R\x06offset\x12\x1d\n" +
	"\n" +
	"total_size\x18\a \x01(\x04R\ttotalSize\x12\x1a\n" +
	"\bchecksum\x18\b \x01(\rR\bchecksum\x12\x12\n" +
	"\x04data\x18\t \x01(\fR\x04data\x12\x16\n" +
	"\x06voters\x18\n" +
	" \x03(\x04R\x06voters\x12!\n" +
	"\fjoint_voters\x18\v \x03(\x04R\vjointVoters\x12)\n" +
	"\x10membership_index\x18\f \x01(\x04R\x0fmembershipIndex\"\xf4\x01\n" +
	"\aCommand\x129\n" +
	"\toperation\x18\x01 \x01(\x0e2\x1b.lsmdb.v1.Command.OperationR\toperation\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\x12\x1b\n" +
	"\tclient_id\x18\x04 \x01(\tR\bclientId\x12\x1f\n" +
	"\vrequest_seq\x18\x05 \x01(\x04R\n" +
	"requestSeq\"H\n" +
	"\tOperation\x12\x12\n" +
	"\x0eOPERATION_NOOP\x10\x00\x12\x11\n" +
	"\rOPERATION_PUT\x10\x01\x12\x14\n" +
	"\x10OPERATION_DELETE\x10\x022\xc2\x02\n" +
	"\x02KV\x124\n" +
	"\x03Put\x12\x14.lsmdb.v1.PutRequest\x1a\x17.lsmdb.v1.WriteResponse\x12:\n" +
	"\x06Delete\x12\x17.lsmdb.v1.DeleteRequest\x1a\x17.lsmdb.v1.WriteResponse\x122\n" +
	"\x03Get\x12\x14.lsmdb.v1.GetRequest\x1a\x15.lsmdb.v1.GetResponse\x12;\n" +
	"\x06Status\x12\x17.lsmdb.v1.StatusRequest\x1a\x18.lsmdb.v1.StatusResponse\x12Y\n" +
	"\x10ChangeMembership\x12!.lsmdb.v1.ChangeMembershipRequest\x1a\".lsmdb.v1.ChangeMembershipResponse2y\n" +
	"\x04Raft\x120\n" +
	"\x04Send\x12\x15.lsmdb.v1.RaftMessage\x1a\x11.lsmdb.v1.RaftAck\x12?\n" +
	"\x0fInstallSnapshot\x12\x17.lsmdb.v1.SnapshotChunk\x1a\x11.lsmdb.v1.RaftAck(\x01B\x1cZ\x1alsmdb/api/lsmdb/v1;lsmdbv1b\x06proto3"

var (
	file_api_lsmdb_v1_lsmdb_proto_rawDescOnce sync.Once
	file_api_lsmdb_v1_lsmdb_proto_rawDescData []byte
)

func file_api_lsmdb_v1_lsmdb_proto_rawDescGZIP() []byte {
	file_api_lsmdb_v1_lsmdb_proto_rawDescOnce.Do(func() {
		file_api_lsmdb_v1_lsmdb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_lsmdb_v1_lsmdb_proto_rawDesc), len(file_api_lsmdb_v1_lsmdb_proto_rawDesc)))
	})
	return file_api_lsmdb_v1_lsmdb_proto_rawDescData
}

var file_api_lsmdb_v1_lsmdb_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_lsmdb_v1_lsmdb_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_api_lsmdb_v1_lsmdb_proto_goTypes = []any{
	(Command_Operation)(0),           // 0: lsmdb.v1.Command.Operation
	(*PutRequest)(nil),               // 1: lsmdb.v1.PutRequest
	(*DeleteRequest)(nil),            // 2: lsmdb.v1.DeleteRequest
	(*WriteResponse)(nil),            // 3: lsmdb.v1.WriteResponse
	(*GetRequest)(nil),               // 4: lsmdb.v1.GetRequest
	(*GetResponse)(nil),              // 5: lsmdb.v1.GetResponse
	(*StatusRequest)(nil),            // 6: lsmdb.v1.StatusRequest
	(*Peer)(nil),                     // 7: lsmdb.v1.Peer
	(*StatusResponse)(nil),           // 8: lsmdb.v1.StatusResponse
	(*ChangeMembershipRequest)(nil),  // 9: lsmdb.v1.ChangeMembershipRequest
	(*ChangeMembershipResponse)(nil), // 10: lsmdb.v1.ChangeMembershipResponse
	(*NotLeader)(nil),                // 11: lsmdb.v1.NotLeader
	(*LogEntry)(nil),                 // 12: lsmdb.v1.LogEntry
	(*RaftMessage)(nil),              // 13: lsmdb.v1.RaftMessage
	(*RaftAck)(nil),                  // 14: lsmdb.v1.RaftAck
	(*SnapshotChunk)(nil),            // 15: lsmdb.v1.SnapshotChunk
	(*Command)(nil),                  // 16: lsmdb.v1.Command
}
var file_api_lsmdb_v1_lsmdb_proto_depIdxs = []int32{
	7,  // 0: lsmdb.v1.StatusResponse.peers:type_name -> lsmdb.v1.Peer
	12, // 1: lsmdb.v1.RaftMessage.entries:type_name -> lsmdb.v1.LogEntry
	0,  // 2: lsmdb.v1.Command.operation:type_name -> lsmdb.v1.Command.Operation
	1,  // 3: lsmdb.v1.KV.Put:input_type -> lsmdb.v1.PutRequest
	2,  // 4: lsmdb.v1.KV.Delete:input_type -> lsmdb.v1.DeleteRequest
	4,  // 5: lsmdb.v1.KV.Get:input_type -> lsmdb.v1.GetRequest
	6,  // 6: lsmdb.v1.KV.Status:input_type -> lsmdb.v1.StatusRequest
	9,  // 7: lsmdb.v1.KV.ChangeMembership:input_type -> lsmdb.v1.ChangeMembershipRequest
	13, // 8: lsmdb.v1.Raft.Send:input_type -> lsmdb.v1.RaftMessage
	15, // 9: lsmdb.v1.Raft.InstallSnapshot:input_type -> lsmdb.v1.SnapshotChunk
	3,  // 10: lsmdb.v1.KV.Put:output_type -> lsmdb.v1.WriteResponse
	3,  // 11: lsmdb.v1.KV.Delete:output_type -> lsmdb.v1.WriteResponse
	5,  // 12: lsmdb.v1.KV.Get:output_type -> lsmdb.v1.GetResponse
	8,  // 13: lsmdb.v1.KV.Status:output_type -> lsmdb.v1.StatusResponse
	10, // 14: lsmdb.v1.KV.ChangeMembership:output_type -> lsmdb.v1.ChangeMembershipResponse
	14, // 15: lsmdb.v1.Raft.Send:output_type -> lsmdb.v1.RaftAck
	14, // 16: lsmdb.v1.Raft.InstallSnapshot:output_type -> lsmdb.v1.RaftAck
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_api_lsmdb_v1_lsmdb_proto_init() }
func file_api_lsmdb_v1_lsmdb_proto_init() {
	if File_api_lsmdb_v1_lsmdb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_lsmdb_v1_lsmdb_proto_rawDesc), len(file_api_lsmdb_v1_lsmdb_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_api_lsmdb_v1_lsmdb_proto_goTypes,
		DependencyIndexes: file_api_lsmdb_v1_lsmdb_proto_depIdxs,
		EnumInfos:         file_api_lsmdb_v1_lsmdb_proto_enumTypes,
		MessageInfos:      file_api_lsmdb_v1_lsmdb_proto_msgTypes,
	}.Build()
	File_api_lsmdb_v1_lsmdb_proto = out.File
	file_api_lsmdb_v1_lsmdb_proto_goTypes = nil
	file_api_lsmdb_v1_lsmdb_proto_depIdxs = nil
}
